### ISSUE TITLE
Can't find cuda in docker

### ISSUE THREAD

**Issue by Huijie2020** [TonyXuQAQ/Topo-boundary#1]
Hi,
Per our previous conversation over email, there should be CUDA  11.0 installed in the docker image but I can't find (other packages like Torch 1.7.0 are fine).

Here are my steps: 
1. I followed the directions to install docker and ran build_image.sh to build the docker.
2. start the docker by `sudo docker run -it zhxu_topoboundary`.
3. type `nvidia-smi` but command not found.

Is there any extra steps missing from my installation?

Thanks!

**Comment by TonyXuQAQ** [comment]
Hi Huijie,

It seems that you did not mount any gpu. Try docker run --gpus all -it
zhxu_topoboundary. It should work. Besides, you can directly run the bash
file ./build_container.bash under any directory of the baselines to create
a container.

Best regards,
Zhenhua

**Comment by Huijie2020** [comment]
Hi Zhenhua,

I type sudo docker run --gpus all -it zhxu_topoboundary and mount gpu successfully. I can find cuda by typying nvidia-smi but the version is 10.1 which is the same version as the host machine. Is it Okay to use cuda 10.1 to run the code? Is there any fast way to test if I set the environment successfully?

Thank you very much!

Best,
Huijie

**Comment by TonyXuQAQ** [comment]
Hi huijie. For better records of the issue, I deleted the email and answer your questions again here with markdown.

For the first question: 
It seems that you did not mount any gpu. Try ```docker run --gpus all -it zhxu_topoboundary```. It should work. Besides, you can directly run the bash file ```./build_container.bash``` under any directory of the baselines to create a container.

For the second question:
I think it should do. We upgraded CUDA to 11 simply for the RTX3090. If CUDA10.1 does not work, please let us know and we will run more tests.

**Comment by Huijie2020** [comment]
Thank you! I will try and let you know.

**Comment by Huijie2020** [comment]
> Hi huijie. For better records of the issue, I deleted the email and answer your questions again here with markdown.
> 
> For the first question:
> It seems that you did not mount any gpu. Try `docker run --gpus all -it zhxu_topoboundary`. It should work. Besides, you can directly run the bash file `./build_container.bash` under any directory of the baselines to create a container.
> 
> For the second question:
> I think it should do. We upgraded CUDA to 11 simply for the RTX3090. If CUDA10.1 does not work, please let us know and we will run more tests.

Thank you! I will try and let you know.

**Comment by Huijie2020** [comment]
> Hi huijie. For better records of the issue, I deleted the email and answer your questions again here with markdown.
> 
> For the first question:
> It seems that you did not mount any gpu. Try `docker run --gpus all -it zhxu_topoboundary`. It should work. Besides, you can directly run the bash file `./build_container.bash` under any directory of the baselines to create a container.
> 
> For the second question:
> I think it should do. We upgraded CUDA to 11 simply for the RTX3090. If CUDA10.1 does not work, please let us know and we will run more tests.

Thank you! I will try and let you know.

**Comment by Huijie2020** [comment]
> Hi huijie. For better records of the issue, I deleted the email and answer your questions again here with markdown.
> 
> For the first question:
> It seems that you did not mount any gpu. Try `docker run --gpus all -it zhxu_topoboundary`. It should work. Besides, you can directly run the bash file `./build_container.bash` under any directory of the baselines to create a container.
> 
> For the second question:
> I think it should do. We upgraded CUDA to 11 simply for the RTX3090. If CUDA10.1 does not work, please let us know and we will run more tests.

I tested naive_baseline evaluation, and CUDA10.1 worked.
Thank you!
