### ISSUE TITLE
When load './checkpoints/seg_8.pth', i got this error

### ISSUE THREAD

**Issue by cl886699** [TonyXuQAQ/Topo-boundary#10]
Start segmentation of OrientationRefine...
Device:  cuda:0
Batch size:  2
Mode:  infer_train
Checkpoint ./checkpoints/seg_8.pth
=======================
Finish loading the training data set lists 10000!
Finish loading the test data set lists 10236!
Traceback (most recent call last):
  File "train_seg.py", line 199, in <module>
    net.load_state_dict(torch.load(args.load_checkpoint, map_location='cpu'))
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for StackHourglassNetMTL:
	size mismatch for conv1.weight: copying a param with shape torch.Size([64, 4, 7, 7]) from checkpoint, the shape in current model is torch.Size([64, 5, 7, 7]).
	size mismatch for score_2.0.weight: copying a param with shape torch.Size([64, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([65, 128, 1, 1]).
	size mismatch for score_2.0.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([65]).
	size mismatch for score_2.1.weight: copying a param with shape torch.Size([64, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([65, 128, 1, 1]).
	size mismatch for score_2.1.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([65]).
	size mismatch for _score_2.0.weight: copying a param with shape torch.Size([128, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([128, 65, 1, 1]).
	size mismatch for angle_decoder1_score.weight: copying a param with shape torch.Size([64, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([65, 128, 1, 1]).
	size mismatch for angle_decoder1_score.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([65]).
	size mismatch for angle_finalconv3.weight: copying a param with shape torch.Size([64, 32, 2, 2]) from checkpoint, the shape in current model is torch.Size([65, 32, 2, 2]).
	size mismatch for angle_finalconv3.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([65]).

 Maybe the parameter of 'task2_classes' should be 64 on line 159 of  'topoBoundary/segmentation_based_baselines/OrientationRefine/model/stack_module.py'

**Comment by TonyXuQAQ** [comment]
Sorry for the inconvenience. I have tested the code and checkpoints, they work fine on my machine. Do you use the latest version of the provided pretrain checkpoints (updated in Jul/2)? At the early stage, ```task2_classes``` was set as 64, but it has been already changed to 65. 

If using the latest version of the checkpoints does not solve your problem, please let us know. We will check whether there is any version management issue.

**Comment by cl886699** [comment]
> updated in Jul/2
The models are in May/18. I downloaded them from https://drive.google.com/uc?id=1xasG1LEeBuB-MmdiMGaX1jgZN8ThW3Jd

**Comment by TonyXuQAQ** [comment]
We have found the problem, please allow us to have some time for correction. We will let you know when it is solved. Sorry for the inconvenience.

**Comment by TonyXuQAQ** [comment]
The bug is fixed. Sorry to keep you waiting. We did not re-train OrientationRefine and updated the provided pretrain-checkpoints after making modifications to the code. Now we re-train it and upload the latest checkpoints onto Google Drive. Please run the script ```get_checkpoints.bash``` in ```./dataset``` folder.

**Comment by cl886699** [comment]
Thank you very much. It's nice work.
