### ISSUE TITLE
Inferencing new images

### ISSUE THREAD

**Issue by Weixing-Zhang** [TonyXuQAQ/Topo-boundary#17]
Hi Zhenhua and other authors,

I was trying to run inferencing with completely new 1000 by 1000 aerial images using "iCurb". It turned out that the model required label information from the "./dataset/labels/dense_seq/xxx.json." However, most label data are provided with a Google Download link. 

I wonder if there is a way to calculate all the required label information for inferencing new images. Any help would be much appreciated.

**Comment by TonyXuQAQ** [comment]
For new image inference, it seems that you do not need gt labels which are only for evaluation score calculation. You may generate the initial points manually or by ```./graph_based_baselines/init_vertex```.

Hope this helps.

**Comment by Weixing-Zhang** [comment]
That's right. New image inferencing does not require gt labels but seems to require the gt sequence. For instance, in `./graph_based_baselines/iCurb/main_val.py` line 101, the implementation code requires `init_points` to record generated vertices (see the attached link below)

https://github.com/TonyXuQAQ/Topo-boundary/blob/master/graph_based_baselines/iCurb/main_val.py#:~:text=for%20v_idx%2Cinit_point%20in%20enumerate(init_points)%3A

Thank you for the direction. I tried to generate the initial points by `./graph_based_baselines/init_vertex`. It turnsd out it requires `bindary map` from the `./dataset/labels` folder. 

I wonder if you know how I can infer new images without any dependency on the `./dataset/labels`. I really appreciate your generous help.

**Comment by TonyXuQAQ** [comment]
Sorry that the code of this repo is too long ago, please allow me to check the issue tomorrow. I will give you feedback ASAP.

**Comment by TonyXuQAQ** [comment]
After going through the code, the labels loaded from ```./dataset/labels``` in inference scripts are only used for evaluation metrics calculation, which could be found here: [link](https://github.com/TonyXuQAQ/Topo-boundary/blob/dd2ed00fc8ccbe42661d44b80497f34f1aaa039a/graph_based_baselines/init_vertex/eval.py#L88). You can comment out this line, lines in the dataloader for label loading (e.g., [data loader line](https://github.com/TonyXuQAQ/Topo-boundary/blob/dd2ed00fc8ccbe42661d44b80497f34f1aaa039a/graph_based_baselines/init_vertex/eval.py#L31)) and other corresponding lines. (Only doing inference without evaluation).

Then your pipeline is like: (1) generate initial vertices -> (2) run iCurb or Enhanced-iCurb with generated initial vertices. Ignore the evaluation calculation in each step, so you need to comment out corresponding lines and alter the dataloader, which should be simple.

Hope this could help.

**Comment by Weixing-Zhang** [comment]
@TonyXuQAQ 

Thank you very much for your promoted reply. I finally made everything work with your suggestions.
