### ISSUE TITLE
Retraining Enhanced-iCurb is slow

### ISSUE THREAD

**Issue by Weixing-Zhang** [TonyXuQAQ/Topo-boundary#18]
Dear Xu, 

I apologize for bugging you again here but would be greatly appreciated to hear your thoughts. I tried to retrain the Enhanced-iCurb model with 3-channel (RGB only) images and wanted to see the effect of removing the NIR channel. 

I learned that the retraining process was very slow mainly because of the validation for 150 images after training each image. It only trained about 500 images for 72 hours (on a gtx1080ti). The validation was very slow. The following are my two questions:
(1) You might have tried your model with 3-channel images. Was it as good as the 4-channel one if you have done that?  Never mind if you have not. I am happy to let you know the result if I have any.
(2) Is there a faster way to retrain the model? For example, are validating the 150 images necessary after training one image? 

Thank you so much in advance.

**Comment by TonyXuQAQ** [comment]
Thanks for the questions. The main reason for the inefficiency of iCurb is that we conducted online sampling (DAgger), which means during the training, we generate training samples for imitation learning online, and it takes a lot of time. If you think it is unnecessary and unacceptable, you might generate the samples in an offline manner: (1) generate imitation learning samples before training -> (2) train the network without sampling. The inefficiency could be seen as one drawback of imitation learning.

For the questions, (1) Yes we have tried training with only RGB channels, and the results are a little bit inferior to using 4-channels. iCurb should work well with RGB images. (2) As I mentioned before, sampling is one factor that affects speed. Other possible ways for better efficiency: (a). enlarge the step size of iCurb agent (b). decrease the frequency of validation (c) use a more powerful CPU, etc. Validation is only for checking the performance of the model during training, of course you can alter the frequency of validation based on your need. BTW, if iCurb is not well trained, the agent may have very strange behaviors, such as halts on a single pixel, or moves around a very small region (the iCurb is trapped), which could extremely enlarge the validation and inference time.

**Comment by Weixing-Zhang** [comment]
Hi Xu. That's super informative and helpful. I will be trying to follow your insights and see if I can reduce the training time without compromising the model performance. 

I noticed the following interesting findings when applying the model to new data (same specs as the shared dataset). I wonder why some edges in the picture do not have vertices but some do. The ones that have vertices seem to be more accurate than the ones without vertices. And then I traced back to the "init_vertex" model and found that seems to be the root cause. In other words, the performance of iCurb highly depends on the "init_vertex" model. I will need to take another close look at your article and understand it better. Any thoughts are welcome to share. : )

![image](https://user-images.githubusercontent.com/10710457/180998284-a5056f25-53dc-4cc3-9aec-9a092fb0be97.png)

**Comment by TonyXuQAQ** [comment]
Grad to hear that my info helps! 

For the provided figure, the yellow nodes are generated vertices and orange lines are edges. They are the trajectory of the trained agent, and it is weird that some edges have no vertices on them (all oranges lines should have yellow nodes on them). This could be a visualization bug (which is not caused by initi_vertex), but it does not affect the performance of iCurb (or Enhanced-iCurb).

Initial vertices are very important for iCurb since they provide starting points to start the iteration of iCurb. Each initial vertex represents one road boundary instance, and iCurb will generate the graph of this instance starting from the corresponding initial vertex. When iCurb reaches the end vertex of this instance, it moves to other initial vertices and repeats the aforementioned process. Since locating initial vertices manually is not a heavy load, we suggest you fix initial vertices manually after initial vertex prediction for better performance.

**Comment by Weixing-Zhang** [comment]
I lowered the frequency of validation and it is definitely faster than it was. Thank you so much.

Very good point. Compared to manually outlining the road boundaries, manually creating the initial vertices seems to be a good compromise. Given the discussion above, locating the initial vertices is the key to further improving the model. I believe you and other authors might have been working towards that and look forward to seeing more exciting work from the team.

Just out of curiosity if you do not mind, does the team has any plan to make the data preparation code publicly available (generating the label datasets from the pavement_edge)? I saw the CUDA code for generating the inverse distance and direction maps. No worries if that is not on your horizon.

**Comment by TonyXuQAQ** [comment]
Since we did not prepare corresponding scripts for label generation, we plan to clean and prepare these scripts at a later stage. You could refer to the [supplementary document](https://tonyxuqaq.github.io/assets/pdf/topoboundary_supplementary.pdf) for information of labels.

**Comment by Weixing-Zhang** [comment]
Understood. Thank you very very much for your help.
