### ISSUE TITLE
reproducing orientation map

### ISSUE THREAD

**Issue by Weixing-Zhang** [TonyXuQAQ/Topo-boundary#19]
Hi Xu,

I ran into a few issues while trying to reproduce the code to generate orientation maps from binary maps. I got some preliminary results by leveraging OrientationRefine Paper's implementation but they seem to be very different than the provided orientation maps. I sensed that you might implement the conversion in a different way as I carefully looked through the "Supplementary document for Topo-Boundary."

(1) Does the actual value in the orientation map matter? The key seems to be that the pixels on boundaries that have different directions should have different values. Likewise, the pixels on boundaries that have the same direction should have the same value. The model should work, right? 

(2) It was mentioned that pixel value p is the angle between the road boundary and the v axis. Is that v-axis pointing to 3/2 pi (i.e., 270 degrees)?

(3) I am not sure how abs(p) = 32Theta / pi relates to 64-class classification. Should we calculate the abs(p) first and then group them into 64 classes consequently?

I know that you mentioned someone else generated the preprocessing data but you will be releasing the data preprocessing in the near future. I wonder if you would be willing to share a snippet of the binary_map to orientation_map implementation even though they may have not been cleaned and refactored. 

Any help is much appreciated. My email is 

weixing.zhang365@gmail.com

**Comment by TonyXuQAQ** [comment]
Thanks for the questions.
1. Yes, the exact value does not matter.
2. Yes, the $\frac{3}{2}\pi$ is the zero angle.
3. $\pi$ is split into 32 classes thus $2\pi$ into 64 classes. More strictly speaking, there are 65 classes, 64 discrete angles plus one background class.

We just uploaded the script for label generation [label generation script (untested)](https://github.com/TonyXuQAQ/Topo-boundary/blob/master/dataset/label_generation_untested/processing.py), but it is not well tested in the current environment, hope it helps.

**Comment by Weixing-Zhang** [comment]
Got it. Thank you for answering my questions. They are super helpful.
