### ISSUE TITLE
test Enhanced-iCurb by initial vertices generated by trained model instead of GT initial vertices

### ISSUE THREAD

**Issue by ChenccLOL** [TonyXuQAQ/Topo-boundary#24]
Thanks for you great work, i have trained and got a great model to generate graph by  GT initial vertices, but when i tried to test it by generated initial vertices, something went wrong.In trainning data,  GT initial vertices are divided into two categories:init_vertex, end_vertex, and agent begined with init_vertex.when i used all generated initial vertice to test Enhanced-iCurb,i got very bad result.Simultaneously, in init_vertices part, i could’nd know how to classify generated initial vertices into two categories.
Is there something wrong with my operation or by design?
Looking forward to your reply

**Comment by TonyXuQAQ** [comment]
Thanks for the question. Did you use the provided scripts? They should work fine. Could you please provide the visualization of the obtained graph?

In our experiments, we only predict the segmentation map of initial vertices and do not split them into init_vertex and end_vertex. We start to detect the graph starting from all initial vertices. At each step, we will remove those initial vertices that are too closed to the detect graph (trajectory of the agent in the past). So, if the predicted initial vertices are corrected detected, the final graph detection result should be fine.

**Comment by ChenccLOL** [comment]
Thanks for your reply. I have used the provided scripts, here is one of the obtained graph by generated initial vertices：
![990190_01](https://user-images.githubusercontent.com/124565501/217127707-9cd3e859-678d-4959-8318-1dbd0fd88d3f.png)
the segmentation result is as follows(990190_01.tiff)：
![990190_01](https://user-images.githubusercontent.com/124565501/217128014-30e285df-eaf6-47cd-b61c-4e139f1166b3.png)
![990190_01](https://user-images.githubusercontent.com/124565501/217128049-9a467d1a-79eb-4d49-b264-edc715f64c4c.png)
the generated initial vertices are:[[10,124], [10,212], [9, 675], [9, 750], [514, 10], [575, 9], [988, 824], [988, 900]]

graph generate by GT initial vertices is as follows：
![990190_01](https://user-images.githubusercontent.com/124565501/217128176-2c30f2ab-7830-4886-8618-61504ae918b5.png)
the GT initial vertices are: 
initial_vertice:[574, 0]
end_vertice:[999, 827]

I was confused by this discrepancy because i thought the predicted initial vertices are corrected.
Looking forward to your reply

**Comment by TonyXuQAQ** [comment]
It seems that the coordinates of initial vertices are incorrect. This repo is an early work, and there could exist some unexpected incorrect coordinate conventions. Apologize for those unsatisfactory results. Please exchange the x,y values of the predicted initial vertices (e.g., [10,124]->[124,10]).

**Comment by ChenccLOL** [comment]
Thanks for your reply.The visualization of the vertices is as follows（red represents the predicted initial vertices, yellow represents the GT）：
![img_v2_9030f4e5-c637-47a1-8068-fec4583b8fbg](https://user-images.githubusercontent.com/124565501/218654806-075c1e32-ff33-40ac-bc6d-fdebccc4e437.png)
It seems that there is no problem with the x,y values of the predicted initial vertices. Is it because the prediction results are not accurate enough to cause such results or the training of Enhanced-iCurb is not complete enough?
Looking forward to your reply.

**Comment by TonyXuQAQ** [comment]
@ChenccLOL Sorry to bother. Recently the server saving our data has been cleaned. Do you have the downloaded labels.zip and pretrain_checkpoints.zip? Could you please send me a copy? Since we cannot not find the backup data. Thank you so much for your sincere help!

**Comment by ChenccLOL** [comment]
> @ChenccLOL Sorry to bother. Recently the server saving our data has been cleaned. Do you have the downloaded labels.zip and pretrain_checkpoints.zip? Could you please send me a copy? Since we cannot not find the backup data. Thank you so much for your sincere help!
Sorry for just seeing the message. I have looked for the files you mentioned, and I have backups of them. Do you still need them?
