### ISSUE TITLE
Does the training code support resuming checkpoints?

### ISSUE THREAD

**Issue by Huijie2020** [TonyXuQAQ/Topo-boundary#4]
Hi,

Does the training code support resuming checkpoints? If not, do we have any plans to support in the future?

Thank you!

**Comment by TonyXuQAQ** [comment]
Sounds easy to implement. I mark this issue as a new feature requirement. At the current stage, you can manually load the saved checkpoint and train your model based on it.

**Comment by TonyXuQAQ** [comment]
I'm closing this issue as a reminder for new features.
