### ISSUE TITLE
Would you update ConvBoundary and Dagmapper code?

### ISSUE THREAD

**Issue by Huijie2020** [TonyXuQAQ/Topo-boundary#5]
Hi Zhenhua,

Thank you very much for your work. It helped me a lot. Would you update ConvBoundary and Dagmapper code recently?

Best,
Huijie

**Comment by TonyXuQAQ** [comment]
It should take another month to clean and accelerate the code since I'm busy with other issues these days. Sorry for the inconvenience :)

**Comment by Huijie2020** [comment]
Sure. Thank you. I am closing the issue.
