### ISSUE TITLE
Question about sampled_seq

### ISSUE THREAD

**Issue by Huijie2020** [TonyXuQAQ/Topo-boundary#6]
Hi Zhenhua,

Thank you very much for your work. 
I run the code with a dataset which has json ground truth, and would like to evaluate APLS. The Topo-boundary code requires pickle ground truth for APLS metric. Could you please share the code to generate pickle file from json?

Thanks!

Best,
Huijie

**Comment by TonyXuQAQ** [comment]
Hi Huijie,

Thanks for the question. I have added a script for this purpose in ```./dataset/scripts/APLS_sample_gt.py```, which should suffice. You should set ```json_dir``` and ```pickle_dir``` based on your file structure. Actually, this script is similar to the function ```generate_graph()``` in the ```utils/eval_metric.py``` script of each baseline model.

The JSON file should record the dense (rasterized) road boundary. And the above script will simplify the dense graph (sample 1 vertex output of 30) to accelerate APLS calculation. You could refer to **Section2.1** and **Figure. 5** in our supplementary document for details.

If you encounter any problems when you adapt our code to your own dataset, please let us know :)

Best,
Zhenhua

**Comment by Huijie2020** [comment]
Thank you very much, Zhenhua! It's very helpful. I am closing the issue.
